# Generated by Django 5.1 on 2024-08-13 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('design_type', models.CharField(choices=[('Website Design', 'Website Design'), ('Mobile Design', 'Mobile Design'), ('Web App Design', 'Web App Design')], max_length=25)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='project_covers/')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDetailImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_images/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_images', to='website.project')),
            ],
        ),
    ]
