# Generated by Django 5.1 on 2024-08-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('testimony', models.TextField()),
                ('stars', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='testimonial_images/')),
            ],
        ),
    ]
