# Generated by Django 5.1 on 2024-08-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='stars',
            field=models.IntegerField(default=1),
        ),
    ]
