# Generated by Django 5.1 on 2024-08-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_testimonial_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='testimony',
            field=models.TextField(default=''),
        ),
    ]
